PLAY [Bootstrap instance(s)] *******************************************************************************************************

PLAY [Configure instance(s)] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [localhost]

TASK [edxapp : migrate] ************************************************************************************************************
failed: [localhost] (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-lms"], "delta": "0:00:25.743810", "end": "2021-06-26 10:59:11.401105", "failed": true, "item": "lms", "rc": 1, "start": "2021-06-26 10:58:45.657295", "stderr": "2021-06-26 01:28:49,449 INFO 24435 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125\nSystem check identified some issues:\n\nWARNINGS:\n?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'\n\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode\n?: (mysql.W002) MySQL Strict Mode is not set for database connection 'read_replica'\n\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode\n?: (mysql.W002) MySQL Strict Mode is not set for database connection 'student_module_history'\n\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode\nTraceback (most recent call last):\n  File \"manage.py\", line 121, in <module>\n    execute_from_command_line([sys.argv[0]] + django_args)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 330, in execute\n    output = self.handle(*args, **options)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 204, in handle\n    fake_initial=fake_initial,\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 115, in migrate\n    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 145, in _migrate_all_forwards\n    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 244, in apply_migration\n    state = migration.apply(state, schema_editor)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 109, in __exit__\n    self.execute(sql)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 136, in execute\n    cursor.execute(sql, params)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py\", line 101, in execute\n    return self.cursor.execute(query, args)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\ndjango.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')", "stderr_lines": ["2021-06-26 01:28:49,449 INFO 24435 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125", "System check identified some issues:", "", "WARNINGS:", "?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'", "\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode", "?: (mysql.W002) MySQL Strict Mode is not set for database connection 'read_replica'", "\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode", "?: (mysql.W002) MySQL Strict Mode is not set for database connection 'student_module_history'", "\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode", "Traceback (most recent call last):", "  File \"manage.py\", line 121, in <module>", "    execute_from_command_line([sys.argv[0]] + django_args)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line", "    utility.execute()", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute", "    self.fetch_command(subcommand).run_from_argv(self.argv)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv", "    self.execute(*args, **cmd_options)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 330, in execute", "    output = self.handle(*args, **options)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 204, in handle", "    fake_initial=fake_initial,", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 115, in migrate", "    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 145, in _migrate_all_forwards", "    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 244, in apply_migration", "    state = migration.apply(state, schema_editor)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 109, in __exit__", "    self.execute(sql)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 136, in execute", "    cursor.execute(sql, params)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute", "    return self.cursor.execute(sql, params)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__", "    six.reraise(dj_exc_type, dj_exc_value, traceback)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute", "    return self.cursor.execute(sql, params)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py\", line 101, in execute", "    return self.cursor.execute(query, args)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute", "    self.errorhandler(self, exc, value)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler", "    raise errorclass, errorvalue", "django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')"], "stdout": "Operations to perform:\n  Apply all migrations: admin, api_admin, assessment, auth, badges, block_structure, bookmarks, branding, bulk_email, catalog, celery_utils, certificates, commerce, completion, consent, contentserver, contenttypes, cors_csrf, course_action_state, course_goals, course_groups, course_modes, course_overviews, course_structures, courseware, coursewarehistoryextended, crawlers, credentials, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, email_marketing, embargo, enterprise, entitlements, experiments, external_auth, grades, instructor_task, integrated_channel, lms_xblock, microsite_configuration, milestones, mobile_api, notes, oauth2, oauth2_provider, oauth_dispatch, oauth_provider, organizations, programs, redirects, rss_proxy, sap_success_factors, schedules, self_paced, sessions, shoppingcart, site_configuration, sites, social_django, splash, static_replace, status, student, submissions, survey, teams, theming, third_party_auth, track, user_api, util, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xblock_django\nRunning migrations:\n  Applying admin.0002_logentry_remove_auto_add... OK\n  Applying api_admin.0007_delete_historical_api_records... OK\n  Applying auth.0007_alter_validators_add_error_messages... OK\n  Applying auth.0008_alter_user_username_max_length... OK\n  Applying catalog.0005_catalogintegration_long_term_cache_ttl... OK\n  Applying certificates.0009_certificategenerationcoursesetting_language_self_generation... OK\n  Applying certificates.0010_certificatetemplate_language... OK\n  Applying certificates.0011_certificatetemplate_alter_unique... OK\n  Applying certificates.0012_certificategenerationcoursesetting_include_hours_of_effort... OK\n  Applying certificates.0013_remove_certificategenerationcoursesetting_enabled... OK\n  Applying certificates.0014_change_eligible_certs_manager... OK\n  Applying commerce.0007_auto_20180313_0609... OK\n  Applying completion.0001_initial... OK\n  Applying completion.0002_auto_20180125_1510... OK\n  Applying enterprise.0020_auto_20170624_2316... OK\n  Applying enterprise.0021_auto_20170711_0712... OK\n  Applying enterprise.0022_auto_20170720_1543... OK\n  Applying enterprise.0023_audit_data_reporting_flag... OK\n  Applying enterprise.0024_enterprisecustomercatalog_historicalenterprisecustomercatalog...", "stdout_lines": ["Operations to perform:", "  Apply all migrations: admin, api_admin, assessment, auth, badges, block_structure, bookmarks, branding, bulk_email, catalog, celery_utils, certificates, commerce, completion, consent, contentserver, contenttypes, cors_csrf, course_action_state, course_goals, course_groups, course_modes, course_overviews, course_structures, courseware, coursewarehistoryextended, crawlers, credentials, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, email_marketing, embargo, enterprise, entitlements, experiments, external_auth, grades, instructor_task, integrated_channel, lms_xblock, microsite_configuration, milestones, mobile_api, notes, oauth2, oauth2_provider, oauth_dispatch, oauth_provider, organizations, programs, redirects, rss_proxy, sap_success_factors, schedules, self_paced, sessions, shoppingcart, site_configuration, sites, social_django, splash, static_replace, status, student, submissions, survey, teams, theming, third_party_auth, track, user_api, util, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xblock_django", "Running migrations:", "  Applying admin.0002_logentry_remove_auto_add... OK", "  Applying api_admin.0007_delete_historical_api_records... OK", "  Applying auth.0007_alter_validators_add_error_messages... OK", "  Applying auth.0008_alter_user_username_max_length... OK", "  Applying catalog.0005_catalogintegration_long_term_cache_ttl... OK", "  Applying certificates.0009_certificategenerationcoursesetting_language_self_generation... OK", "  Applying certificates.0010_certificatetemplate_language... OK", "  Applying certificates.0011_certificatetemplate_alter_unique... OK", "  Applying certificates.0012_certificategenerationcoursesetting_include_hours_of_effort... OK", "  Applying certificates.0013_remove_certificategenerationcoursesetting_enabled... OK", "  Applying certificates.0014_change_eligible_certs_manager... OK", "  Applying commerce.0007_auto_20180313_0609... OK", "  Applying completion.0001_initial... OK", "  Applying completion.0002_auto_20180125_1510... OK", "  Applying enterprise.0020_auto_20170624_2316... OK", "  Applying enterprise.0021_auto_20170711_0712... OK", "  Applying enterprise.0022_auto_20170720_1543... OK", "  Applying enterprise.0023_audit_data_reporting_flag... OK", "  Applying enterprise.0024_enterprisecustomercatalog_historicalenterprisecustomercatalog..."]}
failed: [localhost] (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-cms"], "delta": "0:00:06.598173", "end": "2021-06-26 10:59:18.162179", "failed": true, "item": "cms", "rc": 1, "start": "2021-06-26 10:59:11.564006", "stderr": "2021-06-26 01:29:16,064 INFO 25170 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125\nSystem check identified some issues:\n\nWARNINGS:\n?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'\n\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode\n?: (mysql.W002) MySQL Strict Mode is not set for database connection 'read_replica'\n\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode\n?: (mysql.W002) MySQL Strict Mode is not set for database connection 'student_module_history'\n\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode\nTraceback (most recent call last):\n  File \"manage.py\", line 121, in <module>\n    execute_from_command_line([sys.argv[0]] + django_args)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 330, in execute\n    output = self.handle(*args, **options)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 204, in handle\n    fake_initial=fake_initial,\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 115, in migrate\n    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 145, in _migrate_all_forwards\n    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 244, in apply_migration\n    state = migration.apply(state, schema_editor)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/migration.py\", line 129, in apply\n    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py\", line 97, in database_forwards\n    schema_editor.create_model(model)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 319, in create_model\n    self.execute(sql, params or None)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 136, in execute\n    cursor.execute(sql, params)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 62, in execute\n    return self.cursor.execute(sql)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py\", line 101, in execute\n    return self.cursor.execute(query, args)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\ndjango.db.utils.OperationalError: (1050, \"Table 'enterprise_enterprisecustomercatalog' already exists\")", "stderr_lines": ["2021-06-26 01:29:16,064 INFO 25170 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125", "System check identified some issues:", "", "WARNINGS:", "?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'", "\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode", "?: (mysql.W002) MySQL Strict Mode is not set for database connection 'read_replica'", "\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode", "?: (mysql.W002) MySQL Strict Mode is not set for database connection 'student_module_history'", "\tHINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode", "Traceback (most recent call last):", "  File \"manage.py\", line 121, in <module>", "    execute_from_command_line([sys.argv[0]] + django_args)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line", "    utility.execute()", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute", "    self.fetch_command(subcommand).run_from_argv(self.argv)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv", "    self.execute(*args, **cmd_options)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 330, in execute", "    output = self.handle(*args, **options)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 204, in handle", "    fake_initial=fake_initial,", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 115, in migrate", "    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 145, in _migrate_all_forwards", "    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 244, in apply_migration", "    state = migration.apply(state, schema_editor)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/migration.py\", line 129, in apply", "    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py\", line 97, in database_forwards", "    schema_editor.create_model(model)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 319, in create_model", "    self.execute(sql, params or None)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/base/schema.py\", line 136, in execute", "    cursor.execute(sql, params)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute", "    return self.cursor.execute(sql, params)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__", "    six.reraise(dj_exc_type, dj_exc_value, traceback)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/utils.py\", line 62, in execute", "    return self.cursor.execute(sql)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py\", line 101, in execute", "    return self.cursor.execute(query, args)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute", "    self.errorhandler(self, exc, value)", "  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler", "    raise errorclass, errorvalue", "django.db.utils.OperationalError: (1050, \"Table 'enterprise_enterprisecustomercatalog' already exists\")"], "stdout": "Operations to perform:\n  Apply all migrations: admin, api_admin, assessment, auth, block_structure, bookmarks, catalog, celery_utils, completion, consent, contentserver, contentstore, contenttypes, course_action_state, course_creators, course_groups, course_modes, course_overviews, course_structures, courseware, crawlers, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, embargo, enterprise, entitlements, external_auth, integrated_channel, microsite_configuration, milestones, oauth2, oauth2_provider, oauth_provider, organizations, redirects, sap_success_factors, schedules, self_paced, sessions, site_configuration, sites, static_replace, student, submissions, survey, tagging, theming, track, user_api, user_tasks, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xblock_config, xblock_django\nRunning migrations:\n  Applying enterprise.0024_enterprisecustomercatalog_historicalenterprisecustomercatalog...", "stdout_lines": ["Operations to perform:", "  Apply all migrations: admin, api_admin, assessment, auth, block_structure, bookmarks, catalog, celery_utils, completion, consent, contentserver, contentstore, contenttypes, course_action_state, course_creators, course_groups, course_modes, course_overviews, course_structures, courseware, crawlers, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, embargo, enterprise, entitlements, external_auth, integrated_channel, microsite_configuration, milestones, oauth2, oauth2_provider, oauth_provider, organizations, redirects, sap_success_factors, schedules, self_paced, sessions, site_configuration, sites, static_replace, student, submissions, survey, tagging, theming, track, user_api, user_tasks, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xblock_config, xblock_django", "Running migrations:", "  Applying enterprise.0024_enterprisecustomercatalog_historicalenterprisecustomercatalog..."]}

NO MORE HOSTS LEFT *****************************************************************************************************************
	to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: migrate ------------------------------------------------------------------------ 32.76s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Gathering Facts ----------------------------------------------------------------- 0.73s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing:
Playbook Configure instance(s) finished: 2021-06-26 05:29:18.191466, 2 total tasks.  0:00:34.144870 elapsed. 

 
========================================
Ansible failed!

---------------------------------------------------------------------------------------------------------------------------------------------
Reason: THe edxapp database don't have "utf8" charecter set.
Solution: Make the machine fresh and restrored all user databases.
